name: widgetbook_workspace
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Main app
  bloc_architecture:
    path: ../

  # Widgetbook
  widgetbook: ^3.6.0
  widgetbook_annotation: ^3.1.0

  # Copied from main app to support its widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code generation
  build_runner: ^2.4.6
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
