name: ui
description: A Flutter package for the application's user interface, including fonts, themes, and assets.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  colors:
    inputs:
      - assets/color/colors.xml
